micronaut:
  application:
    name: teamGLibrary
  server:
    port: 8888
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - .*
          allowedMethods:
            - POST
            - PUT
            - GET
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        generator:
          access-token:
            expiration: 604800 #7 days in s
        signatures:
          secret:
            generator:
              secret: ***REMOVED***
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        access:
          - isAnonymous()
      - pattern: /redoc/**
        access:
          - isAnonymous()`