micronaut:
  application:
    name: teamGLibrary
  server:
    port: 8888
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - .*
          allowedMethods:
            - POST
            - PUT
            - GET
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ***REMOVED***